/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dfcjkstfxivlwcowdvri"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmY2prc3RmeGl2bHdjb3dkdnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMDM4NDIsImV4cCI6MjA4MDY3OTg0Mn0.kp0mSE6-KedtfmgoOEsID8C_csZGUlsB8glm3kHS4g4"

